import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import path from 'path'

export default defineConfig({
  plugins: [react()],
  test: {
    // Use threads pool instead of forks - forks deadlocks in the
    // hermes-cron sandbox environment causing Phase 2 gate timeout
    pool: 'threads',
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],
    globals: true,
    // The live database posture checks need network access and real
    // credentials. They run via `npm run test:db` (vitest.db.config.ts); this
    // suite stays hermetic.
    exclude: ['**/node_modules/**', '**/dist/**', '**/.next/**', 'scripts/db-security.test.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        // Generated by shadcn and not our logic to verify.
        'src/components/ui/**',
        // Ambient declarations emit no code.
        'src/types/**',
        'src/**/*.d.ts',
      ],
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
})
